strike/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search', views.SearchView.as_view(), name='search'),
]

strike/forms.py
from datetime import datetime
from django import forms
from .models import Location


class StrikeFilterForm(forms.Form):
    daterange = forms.CharField(label='Date', max_length=23)
    country__name = forms.ChoiceField(label='Country', choices=())
    province = forms.CharField(label='Province', max_length=100, required=False)
    town = forms.CharField(label='City / Town', max_length=100, required=False)

    def __init__(self, *args, **kwargs):
        super(StrikeFilterForm, self).__init__(*args, **kwargs)
        country_choices = [
            (l, l) for l in Location.objects.all().values_list(
                'country__name', flat=True).distinct()]
        country_choices.append(('all', ''))
        self.fields['country__name'] = forms.ChoiceField(choices=country_choices)

    def get_values(self):
        """
        Get filter unpackable values.
        """
        if not self.is_valid():
            return {}

        # Only retrieve existing data.
        data = {}
        for item in self.cleaned_data:
            if self.cleaned_data[item] not in ['', None]:
                data[item] = self.cleaned_data[item]

        # Set province key
        if 'province' in data:
            data['location'] = data.pop('province')

        # Set country default value
        if data.get('country__name', '') == 'all':
            data.pop('country__name')

        return data

    def clean_daterange(self):
        """
        Parses and validates daterange string.
        """
        error = forms.ValidationError("Date range must be 'mm/dd/yyyy - mm/dd/yyyy'.")

        if not self.is_valid():
            raise error

        daterange = self.cleaned_data['daterange']
        dates = daterange.split(' - ')
        if len(dates) != 2:
            raise error

        try:
            daterange = {
                'date__gte': datetime.strptime(dates[0], '%m/%d/%Y').date(),
                'date__lte': datetime.strptime(dates[1], '%m/%d/%Y').date(),
            }
        except ValueError:
            raise error

        return daterange

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
  </head>

  <body id="page-top">
    {% block base %}
    {% endblock %}

    <!-- Bootstrap and Jquery -->
    <script type="text/javascript" src="http://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />

    <!-- Searchbar autocomplete -->
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>

    <!-- Include Date Range Picker -->
    <script type="text/javascript" src="http://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />



    <!-- Custom scripts for this template -->
    <script src="{% static 'js/drone_strike.js' %}"></script>

    {% block extra_script %}
    {% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load strike_tags %}

{% block title %}
Drone Strike
{% endblock %}

{% block base %}
  <div class="header">
    <img id="logo" src="{% static 'img/logo.png' %}" alt="Treviso theme logo">
    <h2>Drone Strike</h2>
  </div>

  <!-- Filters -->
  <div class="filters">
    <form class="filter-form" action="{% url 'index' %}" method="GET">
      <div class="filter-item">
        <h4>Date</h4>
        <input id="id_daterange" type="text" class="datefilter" name="daterange" value="{{ daterange }}" />
      </div>

      <div id="tbCountries" class="filter-item">
        <h4>Country</h4>
        <select id="id_country__name" name="country__name">
          <option value="all">All Countries</option>
          {% for country in country_filters %}
          <option value="{{ country.title }}">{{ country.title }}</option>
          {% endfor %}
        </select>

      </div>

      <div class="filter-item">
        <h4>Province</h4>
        <input id="id_province" name="province" type="text" placeholder="Select a province."/>
      </div>

      <div class="filter-item">
        <h4>City / Town</h4>
        <input id="id_town" name="town" type="text" placeholder="Select a city." />
      </div>

      <input type="submit" value="Submit">
      <input type="reset" value="Reset">
    </form>


    <form id="searchform" action="{% url 'search' %}" method="GET" accept-charset="utf-8">
       <input id="searchbar" name="search_q" type="text" placeholder="Search Box">
       <input type="submit" value="Submit">
    </form>

  </div>

  <!-- Map -->
  <div id="map"></div>

  <!-- Search results -->
  {% if query and strikes %}
    <div id="search-results">
      <h2>Search results for {{ query }}</h2>

      <ul>
        {% for strike in strikes %}
          <li>
            <span class="strike_id">{{ strike.id}}</span> {{ strike.location.country.name }}, {{ strike.location.town }}
            <p>{{ strike.location.lat }}, {{ strike.location.lon }}</p>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  <!-- Footer -->
  <footer class="footer">
    <div class="footer_container">
      <div class="row">
        <div class="col-md-4 mb-5">
          <h4 class="text-uppercase mb-4">Trello Board</h4>
          <a href="https://trello.com/b/0lMLvIhM/drone-strike">https://trello.com/b/0lMLvIhM/drone-strike</a>
        </div>
        <div class="col-md-4">
          <h4 class="text-uppercase mb-4">GitHub</h4>
          <a href="https://github.com/sasakalaba/drone-strike">https://github.com/sasakalaba/drone-strike</a>
        </div>
        <div class="col-md-4">
          <h4 class="text-uppercase mb-4">Live</h4>
          <a href="http://dronestrike.pythonanywhere.com">http://dronestrike.pythonanywhere.com</a>
        </div>
      </div>
    </div>
  </footer>

  <div class="copyright">
    <div class="container">
      <small>Copyright &copy; Drone Strike 2018</small>
    </div>
  </div>
{% endblock %}

{% block extra_script %}
  <script>
    function initMap() {

      function addMarker(coors, map, content){
        // Add Marker function
        var marker = new google.maps.Marker({
          position: coors,
          map: map
        });

        // Marker information
        var infoWindowHover = new google.maps.InfoWindow({
          content: content
        });

        // Marker listeners
        marker.addListener('mouseover', function(){
          infoWindowHover.open(map, marker);
        });
        marker.addListener('mouseout', function() {
          infoWindowHover.close();
        });

        return marker;
      }

      // Init map
      var base_coor = {lat: 12.89363, lng: 39.88600};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 3.7,
        center: base_coor
      });

      // Create all markers
      var markers = [];
      var content = '';
      {% for location in locations %}
        {% if location.strike_info.detail %}
          content = `
          <h3>#{{ location.strike_info.number }}</h3>
          <p><span style="font-weight: bold;">Date</span>: {{ location.strike_info.date }}</p>
          <p><span style="font-weight: bold;">Deaths</span>: {{ location.strike_info.deaths }}</p>`;
        {% else %}
          content = `
          <h3 style="color: #600000;">{{ location.strike_info.num_of_strikes }} strikes</h3>
          {% for strike in location.strike_info.strikes %}
            <p><span style="font-weight: bold;">{{ strike.number }}</span>: {{ strike.date }}</p>
          {% endfor %}`;
        {% endif %}

        markers.push(addMarker({lat: {{ location.lat }}, lng: {{ location.lon }}}, map, content));
      {% endfor %}

      // Create marker clusters
      var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});

    }
  </script>

  <script>
      $(document).ready(function() {
          // Set date picker
          $('input[name="daterange"]').daterangepicker()

          // Map city filters
          {% for key, value in city_filters.items %}
            var {{ key }}_cities = "{% get_list value %}".split(", ");
          {% endfor %}

          // Map province filters
          {% for key, value in province_filters.items %}
            var {{ key }}_provinces = "{% get_list value %}".split(", ");
          {% endfor %}

          // Dynamic filter options, based on selected country
          $("#tbCountries").change(function() {
              $("#tbCountries option:selected").each(function() {

                // Reset previous entries
                $("#id_province").val("");
                $("#id_town").val("");
                $('#id_province').unbind();
                $('#id_town').unbind();

                // Set new values
                BindControls(eval($(this).val() + '_provinces'), "#id_province");
                BindControls(eval($(this).val() + '_cities'), "#id_town");
              });
          }).trigger("change");
      });

      // function BindControls() {
      function BindControls(countries, selector) {
          $(selector).autocomplete({
              source: countries,
              minLength: 0,
              scroll: true
          }).focus(function() {
              $(this).autocomplete("search", "");
          });
      }
  </script>

  <!-- Google Maps API-->
  <script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_JS_API_KEY }}&libraries=places&callback=initMap" async defer></script>

  <!-- Marker Cluster library -->
  <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
{% endblock %}